version: 2
image: ubuntu:16.04
jobs:
  build:
    docker:
      - image: node:8.12.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run Lint
          command: yarn lint